name: Build

'on':
  push:
    branches:
      - main

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Setup Dependencies
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b $GOPATH/bin v1.24.0
          golangci-lint --version
          go get golang.org/x/tools/cmd/cover
          go get -t -v ./...

      - name: Golang CI Lint
        run: golangci-lint run

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Setup Dependencies
        run: |
          go get golang.org/x/tools/cmd/cover
          go get -t -v ./...

      - name: Run Tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
